const video=document.querySelector('#video'), canvas=document.querySelector('#overlay'), ctx=canvas.getContext('2d');
const result=document.querySelector('#result'), reportButton=document.querySelector('#btn-report'), file=document.querySelector('#file-fallback');
let currentImage=false;
async function startCamera(){try{video.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});}catch(e){show('Camera unavailable: '+e.message+'. Use Upload photo.','error');}}
startCamera();
function show(message,kind=''){result.textContent=message;result.className=kind;}
function specification(){return {length_nominal_mm:document.querySelector('#length-nominal').value,width_nominal_mm:document.querySelector('#width-nominal').value,tolerance_mm:document.querySelector('#tolerance').value};}
function drawImage(source){canvas.width=source.videoWidth||source.naturalWidth;canvas.height=source.videoHeight||source.naturalHeight;ctx.drawImage(source,0,0,canvas.width,canvas.height);canvas.style.display='block';currentImage=true;}
function blobFromCanvas(){return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.92));}
function drawPolygon(points,color){if(!points)return;ctx.strokeStyle=color;ctx.lineWidth=Math.max(2,canvas.width/400);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.stroke();}
function render(data){reportButton.disabled=!data.report_available;if(data.card_box)drawPolygon(data.card_box,'#ffd23f');if(data.box)drawPolygon(data.box,'#36d57a');for(const hole of data.holes||[]){ctx.strokeStyle='#fa5cff';ctx.beginPath();ctx.arc(hole.center[0],hole.center[1],8,0,Math.PI*2);ctx.stroke();}
const lines=[`Status: ${data.inspection_status}`,`Component: ${data.component_type} (AI confidence ${data.identification_confidence}%)`,`Calibration: ${data.calibration_reference}; confidence ${Math.round(data.calibration_confidence*100)}%`,`Measured length x width: ${data.length_mm} x ${data.width_mm} mm`,data.diameter_mm!=null?`Diameter: ${data.diameter_mm} mm`:null,data.hole_to_hole_mm!=null?`Hole-to-hole: ${data.hole_to_hole_mm} mm`:null,`Defects: ${(data.visible_defects||[]).join(', ')||'none flagged'}`,`Verdict: ${data.verdict}`,...(data.verdict_reasons||[])].filter(Boolean);result.replaceChildren(...lines.map(line=>{const p=document.createElement('p');p.textContent=line;return p;}));result.className=data.verdict==='PASS'?'pass':data.verdict==='FAIL'?'fail':'review';}
async function inspectBlob(blob,name){reportButton.disabled=true;show('Inspecting…');const form=new FormData();form.append('image',blob,name);for(const [key,value] of Object.entries(specification()))form.append(key,value);try{const response=await fetch('/api/inspect',{method:'POST',body:form});const data=await response.json();if(!response.ok){show((data.message||data.error)+(data.reject_reason?' ('+data.reject_reason+')':'')+(data.verification_hint?' '+data.verification_hint:''),'error');return;}render(data);}catch(e){show('Request failed: '+e.message,'error');}}
document.querySelector('#btn-photo').onclick=async()=>{if(!video.videoWidth)return show('Wait for the camera preview, then try again.','error');drawImage(video);inspectBlob(await blobFromCanvas(),'capture.jpg');};
document.querySelector('#btn-upload').onclick=()=>file.click();
file.onchange=()=>{const selected=file.files[0];if(!selected)return;const image=new Image();image.onload=()=>{drawImage(image);inspectBlob(selected,selected.name);};image.src=URL.createObjectURL(selected);};
reportButton.onclick=async()=>{try{const response=await fetch('/api/report',{method:'POST'});const type=response.headers.get('content-type')||'';if(!response.ok||!type.includes('application/pdf')){let message='The server did not return a PDF.';try{message=(await response.json()).message||message;}catch(_){}show(message,'error');reportButton.disabled=true;return;}const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download='nebula-inspection-report.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){show('Report download failed: '+e.message,'error');}};
